apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-update-password
  namespace: kube-system
  labels:
    app: ecr-creds-update
    component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecr-update-password
  labels:
    app: ecr-creds-update
    component: rbac
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ecr-update-password
  labels:
    app: ecr-creds-update
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ecr-update-password
subjects:
- kind: ServiceAccount
  name: ecr-update-password
  namespace: kube-system